/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contato: typeof import('./components/Contato.vue')['default']
    Matricula: typeof import('./components/Matricula.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Planos: typeof import('./components/Planos.vue')['default']
    Principal: typeof import('./components/Principal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sobre: typeof import('./components/Sobre.vue')['default']
    Treinadores: typeof import('./components/Treinadores.vue')['default']
  }
}
