/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlunosTabela: typeof import('./components/Administrativo/AlunosTabela.vue')['default']
    Contato: typeof import('./components/LandingPage/Contato.vue')['default']
    CrudTable: typeof import('./components/Administrativo/CrudTable.vue')['default']
    Matricula: typeof import('./components/LandingPage/Matricula.vue')['default']
    NavBar: typeof import('./components/LandingPage/NavBar.vue')['default']
    Planos: typeof import('./components/LandingPage/Planos.vue')['default']
    Principal: typeof import('./components/LandingPage/Principal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecaoAluno: typeof import('./components/Administrativo/SecaoAluno.vue')['default']
    SecaoPlanos: typeof import('./components/Administrativo/SecaoPlanos.vue')['default']
    SecaoTreinadores: typeof import('./components/Administrativo/SecaoTreinadores.vue')['default']
    SideBar: typeof import('./components/Administrativo/SideBar.vue')['default']
    Sobre: typeof import('./components/LandingPage/Sobre.vue')['default']
    Treinadores: typeof import('./components/LandingPage/Treinadores.vue')['default']
  }
}
